In [1]:
import torch

In [2]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))
print(m1.matmul(m2)) # 2 x 1
print(m1.mean())
print(m1.mean(dim=0))
print(m1.mean(dim=1))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[ 5.],
        [11.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [24]:
ft = torch.FloatTensor([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
print(ft.shape)
print(ft.view([-1,3]))
print(ft.view([-1,1, 3]))

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


In [40]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft.shape)
print(ft.squeeze().shape)
print(ft.unsqueeze(-1).shape)

torch.Size([3, 1])
torch.Size([3])
torch.Size([3, 1, 1])


In [43]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())
print(lt.long())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 2, 3, 4])


In [48]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [53]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x,y,z]))
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([1., 1.])
tensor([0., 0.])


In [58]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [84]:
result1 = 0
result2 = 0
def add1(num):
    global result1
    result1 += num
    return result
def add2(num):
    result2 += num
    return result
print(add1(3))
print(add1(7))
print(result1)
try:    
    print(add2(3))
    print(add2(7))
    print(result2)
except Exception as e:
    print(e)

33
33
10
local variable 'result2' referenced before assignment


In [106]:
# torch - linear regression
# requirements with torch
nn = torch.nn
F = torch.nn.functional
optim = torch.optim
# if restart, get same result. random seed set
torch.manual_seed(1)
# train data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[3], [5], [9]])
# initial W,  b
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# set learning rate
lr = 0.0005
# gradient descent
optimizer = optim.SGD([W,b], lr=lr)
# train numbers
nb_epochs = 199999
for epoch in range(nb_epochs + 1):
    # hypothesis
    hypothesis = x_train * W + b
    # cost function
    cost = torch.mean((hypothesis - y_train) ** 2)
    # initial gradient
    optimizer.zero_grad()
    # differential cost function 
    cost.backward()
    # W, b update
    optimizer.step()
    # every 100 cycle log print
    if epoch % 10000 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))
# trained hypothesis
y = W * x_train + b
print(y)
print(y_train)
print(y_train-y)

Epoch    0/199999 W: 0.013, b: 0.006 Cost: 38.333332
Epoch 10000/199999 W: 2.817, b: 0.083 Cost: 0.247086
Epoch 20000/199999 W: 2.945, b: -0.208 Cost: 0.224470
Epoch 30000/199999 W: 2.983, b: -0.296 Cost: 0.222426
Epoch 40000/199999 W: 2.995, b: -0.322 Cost: 0.222241
Epoch 50000/199999 W: 2.998, b: -0.330 Cost: 0.222224
Epoch 60000/199999 W: 2.999, b: -0.332 Cost: 0.222222
Epoch 70000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 80000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 90000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 100000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 110000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 120000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 130000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 140000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 150000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 160000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 170000/199999 W: 3.000, b: -0.333 Cost: 0.222222
Epoch 180000/199999 W: