In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [14]:
# if restart, get same result. random seed set
torch.manual_seed(1)
# train data
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
model = nn.Linear(3,1)
# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
# training
nb_epochs = 100000
for epoch in range(nb_epochs+1):
    # hypothesis
    prediction = model(x_train)
    # cost function 
    cost = F.mse_loss(prediction, y_train)
    # cost -> hypothesis update
    optimizer.zero_grad()
    # differential cost function
    cost.backward()
    # w, b update(parameter update)
    optimizer.step()
    # print log
    if epoch % 10000 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))
# random input value
new_var =  torch.FloatTensor([[85,  90,  105]])
# predition
pred_y = model(new_var)
# print model parameter
print(list(model.parameters()))
print(pred_y)

Epoch    0/100000 Cost: 31584.347656
Epoch 10000/100000 Cost: 0.159584
Epoch 20000/100000 Cost: 0.130602
Epoch 30000/100000 Cost: 0.129314
Epoch 40000/100000 Cost: 0.128685
Epoch 50000/100000 Cost: 0.128067
Epoch 60000/100000 Cost: 0.127441
Epoch 70000/100000 Cost: 0.126823
Epoch 80000/100000 Cost: 0.126210
Epoch 90000/100000 Cost: 0.125611
Epoch 100000/100000 Cost: 0.125005
[Parameter containing:
tensor([[1.2227, 0.6515, 0.1440]], requires_grad=True), Parameter containing:
tensor([0.2054], requires_grad=True)]
tensor([[177.8829]], grad_fn=<AddmmBackward0>)
