In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# simple linear regression model class
class LinearRegressionModel(nn.Module): 
    def __init__(self): #
        super().__init__()
        # model set -> input_dim=1, output_dim=1
        self.linear = nn.Linear(1, 1)
    def forward(self, x):
        return self.linear(x)
# multi variable linear regression model class
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        # model set -> input_dim=3, output_dim=1
        self.linear = nn.Linear(3, 1)
    def forward(self, x):
        return self.linear(x)

In [3]:
# simple linear regression
# if restart, get same result. random seed set
torch.manual_seed(1)
# train data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# get model class
model = LinearRegressionModel()
# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 
# training
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # hypothesis
    prediction = model(x_train)
    # cost function
    cost = F.mse_loss(prediction, y_train)
    # cost -> hypothesis update
    optimizer.zero_grad()
    # differential cost function
    cost.backward()
    # w, b update(parameter update)
    optimizer.step()
    # print log
    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [5]:
# multi variable linear regression
# if restart, get same result. random seed set
torch.manual_seed(1)
# train data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# get model class
model = MultivariateLinearRegressionModel()
# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
# training
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # hypothesis
    prediction = model(x_train)
    # cost function
    cost = F.mse_loss(prediction, y_train)
    # cost -> hypothesis update
    optimizer.zero_grad()
    # differential cost function
    cost.backward()
    # w, b update(parameter update)
    optimizer.step()
    # print log
    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))
# random input value
new_var =  torch.FloatTensor([[85,  90,  105]])
# predition
pred_y = model(new_var)
# print model parameter
print(list(model.parameters()))
print(pred_y)

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
tensor([[184.8070]], grad_fn=<AddmmBackward0>)


In [6]:
new_var =  torch.FloatTensor([[85,  90,  105],[55,  70,  75],[65,  96,  81]])
# predition
pred_y = model(new_var)
# print model parameter
print(list(model.parameters()))
print(pred_y)

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
tensor([[184.8070],
        [129.0909],
        [154.1303]], grad_fn=<AddmmBackward0>)
